### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations-compiler#19]
It's getting more and more difficult to run things in Python 2.7. Python 2 was sunset 1⅓ years ago: https://www.python.org/doc/sunset-python-2/

In general, I think it would be good to move to Python 3 sooner rather than later, so that we don't get stuck debugging compatibility.

I personally use macOS, and Python 2.7 regularly breaks because of many installed version — while Python 3 can usually use a single latest version.

**Comment by suushiemaniac** [comment]
Python provides excellent tooling, namely the `2to3` command line tool. I've tried to address this in https://github.com/thewca/wca-regulations-compiler/pull/20

**Comment by suushiemaniac** [comment]
This issue has jsut become much more significant due to https://github.com/pypa/pypi-support/issues/978

In short (ask me for details) we cannot fetch any upgrades from PyPi on the production and staging machines (which are running Python 2.7) anymore.
